# **CO-1**

## **2. Display future leap years from current year to a final year entered by user.**

In [ ]:
current_year = int(input("Enter the current year: "))
future_year = int(input("Enter the future year: "))

print("\nleap years from",current_year,"to",future_year,"are ")
for year in range(current_year, future_year + 1):
  if(year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(year)

Enter the current year: 2025
Enter the future year: 2040

leap years from 2025 to 2040 are
2028
2032
2036
2040

## **3. List comprehensions:**

**(a) Generate positive list of numbers from a given list of integers**

**(b) Square of N numbers**

**(c) Form a list of vowels selected from a given word**

**(d) List ordinal value of each element of a word (Hint: use ord() to get ordinal values)**

In [ ]:
# a..
nums = [-5,12,14,1,42,-9,-78,-2,9,36,-8]
pos_num = [num for num in nums if num > 0]
print(f'Positive Number are : {pos_num}')

# b...
nums = input("\nEnter numbers separated by spaces: ")
n_sqrt = [int(i) ** 2 for i in nums.split()]
print("Square of N number : ",n_sqrt)

# c...
word = input("\nEnter a word: ")
vowels = [ch for ch in word if ch.lower() in 'aeiou']
print(f'Vowels in the word "{word}" are : {vowels}')

# d...
word = input("\nEnter a word: ")
ord_val = [ord(ch) for ch in word]
print(f'Ordinal Value of the {word} are : {ord_val}')

Positive Number are : [12, 14, 1, 42, 9, 36]

Enter numbers separated by spaces: 5 4 2 1 7
Square of N number :  [25, 16, 4, 1, 49]

Enter a word: hello there
Vowels in the word "hello there " are : ['e', 'o', 'e', 'e']

Enter a word: abc
Ordinal Value of the abc are : [97, 98, 99]

## **4. Count the occurrences of each word in a line of text.**

In [ ]:
text = input("Enter a line of text: ").split()
occu = {}
for ch in text:
  if ch in occu:
    occu[ch] += 1
  else:
    occu[ch] = 1
print("Word occurrences:")
for text, count in occu.items():
    print(f"{text}: {count}")

Enter a line of text: hello there hello there are you there
Word occurrences:
hello: 2
there: 3
are: 1
you: 1

## **5. Prompt the user for a list of integers. For all values greater than 100,store ‘over’ instead.**

In [ ]:
num = list(map(int, input("Enter numbers separated by spaces: ").split()))
num_list = []
for nums in num:
  if int(nums) > 100:
    num_list.append("over")
  else:
    num_list.append(nums)
print(num_list)

Enter numbers separated by spaces: 25 120 85 200
[25, 'over', 85, 'over']

## **6. Store a list of first names. Count the occurrences of ‘a’ within the list**

In [ ]:
name = ['Damon', 'Klaus', 'Elena','Edward', 'Bella']
count_a= 0
for ch in name:
  count_a += ch.lower().count('a')
print(f"Total occurrences of 'a': {count_a}")

Total occurrences of 'a': 5

## **7. Enter 2 lists of integers. Check (a) Whether list are of same length (b) whether list sums to same value (c) whether any value occur in both**

In [ ]:
list_a = list(map(int, input("Enter first list of integers separated by space : ").split()))
list_b = list(map(int, input("Enter second list of integers separated by space : ").split()))

# Check if lists are of same length
same_len = len(list_a) == len(list_b)

# Check if lists sum to same value
same_sum = sum(list_a) == sum(list_b)

# Check if any value occurs in both
common_val = set(list_a) & set(list_b)

# Display results
print(f"\nSame length: {same_len}")
print(f"Same sum: {same_sum}")
print(f"Common values: {list(common_val) if common_val else 'None'}")

Enter first list of integers separated by space : 10 20 30 50 40
Enter second list of integers separated by space : 20 80 90 70 10

Same length: True
Same sum: False
Common values: [10, 20]

## **8. Get a string from an input string where all occurrences of first character replaced with `$`,except first character.  `[eg: onion -> oni‘$’,n]`**

In [ ]:
word = "onion"
first_letter = word[0]
print(f"Modified string : {first_letter + word [1:].replace(first_letter, '$')}")

Modified string : oni$n

## **9. Create a string from given string where first and last characters exchanged.   [eg: python > nythop]**

In [ ]:
word = input("Enter a word: ")
swapped = word[-1] + word [1 : -1] + word[0]
print(swapped)

Enter a word: python
nythop

## **10. Accept the radius from user and find area of circle.**

In [ ]:
radius = int(input("Enter radius of the circle : "))
print(f'Area of Circle {3.14 * radius ** 2 :.2f}')

Enter radius of the circle : 20
Area of Circle 1256.00

## **11. Find biggest of 3 numbers entered.**

In [ ]:
x = int(input("Enter a number : "))
y = int(input("Enter a number : "))
z = int(input("Enter a number : "))
print(f'\nBiggest Numbers is {max(x, y, z)}')

Enter a number : 20
Enter a number : 50
Enter a number : 41
Biggest of 3 numbers 50

## **12. Accept a file name from user and print extension of that**

In [ ]:
file_name = input("Enter file name with extension: ").split('.')
print(f'extension is {file_name[-1]}')

Enter file name with extension: text.csv
extension is csv

## **13. Create a list of colors from comma-separated color names entered by user.Display first and last colors.**

In [ ]:
colors = input("Enter a list of colors name from comma-separated:  ").split(',')
color = [color for color in colors]
print(f'\nFirst Color : {color[0]} \nLast Color : {color[-1]}')

Enter a list of colors name from comma-separated:  red,blue,yellow,green,white

First Color : red
Last Color : white

## **14. Accept an integer n and compute n+nn+nnn.**

In [ ]:
num = input("Enter a Number: ")
res = sum(int(num * i) for i in range(1, 4))
print("Result of n + nn + nnn is:", res)

Enter a Number: 5
Result of n + nn + nnn is: 615

## **15. Print out all colors from color-list1 not contained in color-list2.**

In [ ]:
list_a = set(['Blue', 'Green', 'Red', 'Orange'])
list_b = set(['purple', 'cyan', 'Red', 'Blue'])
print(f'Colors in list_a but not in list_b : {list_a - list_b}')

Colors in list_a but not in list_b : {'Orange', 'Green'}

## **16. Create a single string separated with space from two strings by swapping the character at position 1.**

In [ ]:
word_a = input("Enter first word: ")
word_b = input("Enter second word: ")

swap_a = word_b[0] + word_a[1:]
swap_b = word_a[0] + word_b[1:]
print(f"\nBfore swapping: {word_a + word_b} \nAfter swapping: {swap_a + " " + swap_b}")

Enter first word: hello
Enter second word: world

Bfore swapping: hello world
After swapping: wello  horld

## **17. Sort dictionary in ascending and descending order.**

In [ ]:
name = {22 :'Damon', 47:'Klaus', 18:'Elena',40:'Edward', 20:'Bella'}
print(f'Ascending Order : {sorted(name.items())}\nDescending order : {sorted(name.items(), reverse=True)} ')

Ascending Order : [(18, 'Elena'), (20, 'Bella'), (22, 'Damon'), (40, 'Edward'), (47, 'Klaus')]
Descending order : [(47, 'Klaus'), (40, 'Edward'), (22, 'Damon'), (20, 'Bella'), (18, 'Elena')]

## **18. Merge two dictionaries.**

In [ ]:
dict_1 = {22 :'Damon', 47:'Klaus'}
dict_2 = { 18:'Elena',40:'Edward', 20:'Bella'}

dict_1.update(dict_2)
print("Merged dictionary:", dict_1)
# merged = dict_1 | dict_2, (**dict_1, **dict_2)

Merged dictionary: {22: 'Damon', 47: 'Klaus', 18: 'Elena', 40: 'Edward', 20: 'Bella'}

## **19. Find gcd of 2 numbers.**

In [ ]:
gcd_1 = int(input("Enter a number: "))
gcd_2 = int(input("Enter a number: "))

if gcd_1 > gcd_2:
  smaller = gcd_2
else:
  smaller = gcd_1

for i in range(1, smaller + 1):
  if(gcd_1 % i == 0) and (gcd_2 % i == 0):
    gcd = i
print("The GCD of", gcd_1, "and", gcd_2, "is:", gcd)

Enter a number: 36
Enter a number: 24
The GCD of 36 and 24 is: 12

## **20. From a list of integers, create a list removing even numbers.**

In [ ]:
nums = list(map(int, input("Enter a list of number: ").split()))
rem_even = [num for num in nums if num % 2 != 0]
print("Remove Even from the list : ",rem_even)

Enter a list of number: 1 2 3 4 5 6 7 8 9
Remove Even from the list :  [1, 3, 5, 7, 9]

# **CO2**

## **1. Program to find the factorial of a number**

In [ ]:
num = int(input("Enter a number: "))
fact = 1
for i in range(1, num + 1):
  fact *= i
print(f"Factorial of {num} is: {fact}")

Enter a number: 5
Factorial of 5 is: 120

## **2. Generate Fibonacci series of N terms**

In [ ]:
num = int(input("Enter a number: "))

a, b = 0, 1
print("Fibonacci Series:")
for i in range(num):
  print(a, end=" ")
  a, b = b, a + b

Enter a number: 7
Fibonacci Series:
0 1 1 2 3 5 8

## **3. Find the sum of all items in a list**

In [ ]:
num = list(map(int, input("Enter list of integers separated by space : ").split()))
print("Sum of all items in a list is ",sum(num))

Enter list of integers separated by space : 1 2 3 4 5 6 7 8 9 10
Sum of all items in a list is  55

## **4. Generate a list of four digit numbers in a given range with all their digits even and the number is a perfect square.**

In [ ]:
even_square = []
for num in range(32, 100):
  square = num * num
  if 1000 <= square <= 9999:
    digit = str(square)
    if all(int(d) % 2 == 0 for d in digit):
      even_square.append(square)
print("Four digit perfect square with all even number: ",even_square)

Four digit perfect square with all even number:  [4624, 6084, 6400, 8464]

## **5. Display the given pyramid with step number accepted from user. *Eg*: N=4**
```
1
2 4
3 6 9
4 8 12 16
```

In [ ]:
num = int(input("Enter a number: "))
for i in range(1, num + 1):
  for j in range(1, i + 1):
    print(i* j, end=" ")
  print()

Enter a number: 5
1
2 4
3 6 9
4 8 12 16
5 10 15 20 25

## **6. Count the number of characters (character frequency) in a string.**

In [ ]:
word = str(input("Enter a string: "))
char_feq = {}
for ch in word:
  if ch in char_feq:
    char_feq[ch] += 1
  else:
    char_feq[ch] = 1
print(f"character frequency in this {word} is {char_feq}")

Enter a string: hello world
character frequency in this hello world is {'h': 1, 'e': 1, 'l': 3, 'o': 2, ' ': 1, 'w': 1, 'r': 1, 'd': 1}

## **7. Add ‘ing’ at the end of a given string. If it already ends with ‘ing’, then add ‘ly’.**

In [ ]:
word = str(input("Enter a string: "))

if word[-3:] == "ing":
  word += "ly"
else:
  word += "ing"
print(word)

Enter a string: playing
playingly

## **8. Accept a list of words and return length of longest word.**

In [ ]:
words = input("Enter words separated by space: ").split()

long_word = ""
max_len = 0

for word in words:
  if len(word) > max_len:
    max_len = len(word)
    long_word = word

print(f"Longest word:{long_word} \nLength of longest word: {max_len}")

Enter words separated by space:  panda dolphin  wolf crocodile penguin whale
Longest word:crocodile
Length of longest word: 9

## **9. Construct following pattern using nested loop**
```
*
* *
* * *
* * * *
* * * * *
* * * *
* * *
* *
*

In [ ]:
num = 5

for i in range(1, num + 1):
    print("* " * i)

for i in range(num - 1, 0, -1):
    print("* " * i)

*
* *
* * *
* * * *
* * * * *
* * * *
* * *
* *
*

## **10. Generate all factors of a number.**

In [ ]:
nums = int(input("Enter a number: "))
res = [num for num in range(1, nums + 1) if nums % num == 0]
print(f"Factor of {nums} are : {res} ")

Enter a number: 12
Factor of 12 are : [1, 2, 3, 4, 6, 12]

## **11. Write lambda functions to find area of square, rectangle and triangle.**

In [ ]:
squ_area = lambda side : side * side
rect_area = lambda length, breadth : length  * breadth
tri_area = lambda base, height : 0.5 * base * height

side = eval(input("Enter side of sqaure: " ))
length = eval(input("Enter length of rectangle: " ))
breadth = eval(input("Enter breadth of rectangle: " ))
base = eval(input("Enter base of triangle: " ))
height = eval(input("Enter height of triangle: " ))

print("\nArea of Square:", squ_area(side))
print("Area of Rectangle:", rect_area(length, breadth))
print("Area of Triangle:", tri_area(base, height))

Enter side of sqaure: 8
Enter length of rectangle: 9
Enter breadth of rectangle: 5
Enter base of triangle: 6
Enter height of triangle: 3

Area of Square: 64
Area of Rectangle: 45
Area of Triangle: 9.0

# **CO3**

## **Create a package graphics with modules rectangle, circle and sub-package 3D-graphics with modules cuboid and sphere. Include methods to find area and perimeter of respective figures in each module. Write programs that finds area and perimeter of figures by different importing statements.(Include selective import of modules and import * statements)**





```
"""graphics/
│
├── __init__.py
├── rectangle.py
├── circle.py
│
└── graphics3d/
    ├── __init__.py
    ├── cuboid.py
    └── sphere.py """



# circle
"""def area(r):
  return 3.14 * r * r

def perimeter(r):
  return 2 * 3.14 * r"""

# rectangle
"""def area(l, b):
  return l * b

def perimeter(l, b):
  return 2 * (l + b)"""

# cuboid
"""def area(l, b, h):
  return 2 * (l * b + b * h + l * h)

def perimeter(l, b, h):
  return 4 * (l + b + h)"""

# sphere
"""def area(r):
  return 4 * 3.14 * r * r

def perimeter(r):
  return 2 * 3.14 * r"""
```

In [ ]:
# Import Full Modules
import graphics.rectangle as re
import graphics.circle as ci
import graphics.graphics3d.cuboid as cub
import graphics.graphics3d.sphere as sph

print("Import Full Modules...\n")
print("Circle..")
print("Area circle : ",ci.area(6))
print("perimeter circle  : ",ci.perimeter(6))

print("\nRectangle..")
print("Area Rectangle : ",re.area(12, 18))
print("perimeter Rectangle : ",re.perimeter(12, 18))

print("\nCuboid..")
print("Area Cuboid : ",cub.area(5, 8, 6))
print("perimeter Cuboid : ",cub.perimeter(5, 8, 6))

print("\nSphere..")
print("Area Sphere : ",sph.area(8))
print("perimeter Sphere : ",sph.perimeter(8))


# Selective Import of Functions
from graphics.rectangle import perimeter
from graphics.circle import area
from graphics.graphics3d.cuboid import area
from graphics.graphics3d.sphere import perimeter

print("\n\nSelective Import of Functions...\n")
print("Circle..")
print("Area circle : ",ci.area(9))

print("\nRectangle..")
print("perimeter Rectangle : ",re.perimeter(8, 6))

print("\nCuboid..")
print("Area Cuboid : ",cub.area(4, 7, 5))

print("\nSphere..")
print("perimeter Sphere : ",sph.perimeter(7))

# Using import *
from graphics.rectangle import *
from graphics.circle import *
from graphics.graphics3d.cuboid import *
from graphics.graphics3d.sphere import *

print("\n\nUsing import *...\n")
print("Circle..")
print("Area circle : ",ci.area(8))
print("perimeter circle  : ",ci.perimeter(8))

print("\nRectangle..")
print("Area Rectangle : ",re.area(5, 9))
print("perimeter Rectangle : ",re.perimeter(5, 9))

print("\nCuboid..")
print("Area Cuboid : ",cub.area(4, 8, 7))
print("perimeter Cuboid : ",cub.perimeter(4, 8, 7))

print("\nSphere..")
print("Area Sphere : ",sph.area(9))
print("perimeter Sphere : ",sph.perimeter(9))

Import Full Modules...

Circle..
Area circle :  113.03999999999999
Parameter circle  :  37.68

Rectangle..
Area Rectangle :  216
Parameter Rectangle :  60

Cuboid..
Area Cuboid :  236
Parameter Cuboid :  76

Sphere..
Area Sphere :  803.84
Parameter Sphere :  50.24


Selective Import of Functions...

Circle..
Area circle :  254.34

Rectangle..
Parameter Rectangle :  28

Cuboid..
Area Cuboid :  166

Sphere..
Parameter Sphere :  43.96


Using import *...

Circle..
Area circle :  200.96
Parameter circle  :  50.24

Rectangle..
Area Rectangle :  45
Parameter Rectangle :  28

Cuboid..
Area Cuboid :  232
Parameter Cuboid :  76

Sphere..
Area Sphere :  1017.36
Parameter Sphere :  56.52

# **CO4**

In [ ]:
class Rectangle:
    def __init__(self, l, b):
        self.l = l
        self.b = b

    def area(self):
        return self.l * self.b

    def perimeter(self):
        return 2 * (self.l + self.b)


# Input
l1, b1 = map(int, input("Enter length and breadth of first rectangle: ").split())
l2, b2 = map(int, input("Enter length and breadth of second rectangle: ").split())

# Create objects
rect_1 = Rectangle(l1, b1)
rect_2 = Rectangle(l2, b2)

# Output
print("Area of rectangle 1:", rect_1.area())
print("Perimeter of rectangle 1:", rect_1.perimeter())

print("Area of rectangle 2:", rect_2.area())
print("Perimeter of rectangle 2:", rect_2.perimeter())

print("\nCompare are of two rectangle")

if rect_1.area() == rect_2.area():
  print("Value are Same..")
elif rect_1.area() > rect_2.area():
  print("Rectangle 1 is greater ",rect_1.area())
else:
    print("Rectangle 2 is greater ",rect_2.area())

Enter length and breadth of first rectangle: 8 9
Enter length and breadth of second rectangle: 7 6
Area of rectangle 1: 72
Perimeter of rectangle 1: 34
Area of rectangle 2: 42
Perimeter of rectangle 2: 26

Compare are of two rectangle
Rectangle 1 is greater  72

In [ ]:
class Rectangle:
    def __init__(self, l, b):
        self.l = l
        self.b = b

    def area(self):
        return self.l * self.b

    def perimeter(self):
        return 2 * (self.l + self.b)


# Input
l1, b1 = map(int, input("Enter length and breadth of first rectangle: ").split())
l2, b2 = map(int, input("Enter length and breadth of second rectangle: ").split())

# Create objects
rect_1 = Rectangle(l1, b1)
rect_2 = Rectangle(l2, b2)

# Output
print("Area of rectangle 1:", rect_1.area())
print("Perimeter of rectangle 1:", rect_1.perimeter())

print("Area of rectangle 2:", rect_2.area())
print("Perimeter of rectangle 2:", rect_2.perimeter())

print("\nCompare are of two rectangle")

if rect_1.area() == rect_2.area():
  print("Value are Same..")
elif rect_1.area() > rect_2.area():
    print("Rectangle 1 is greater ",rect_1.area())
else:
    print("Rectangle 2 is greater ",rect_2.area())

Enter length and breadth of first rectangle: 8 9
Enter length and breadth of second rectangle: 7 6
Area of rectangle 1: 72
Perimeter of rectangle 1: 34
Area of rectangle 2: 42
Perimeter of rectangle 2: 26

Compare are of two rectangle
Rectangle 1 is greater  72

# **CO5**

## **1.   Write a Python program to read a file line by line and store it into a list.**

In [ ]:
file_list = []
with open('text.txt', 'r') as file:
    content = file.readlines()
    for line in content:
        file_list.append(line.strip())
print(file_list)

['hello', 'world', 'is', 'the', "python's", 'first', 'program']

## **2. Python program to copy odd lines of one file to other**

In [ ]:
with open("text.txt", "r") as src, open("dest.txt", "w") as des:
    for lno, line in enumerate(src, start=1):
        if lno % 2 != 0:   # odd lines
            try:
                des.write(line)
            except:
                print("Something went wrong")

print("Successfully")

Successfully

## **3. Write a Python program to read each row from a given csv file and print a list of strings.**

In [ ]:
import pandas as pd
df = pd.read_csv('employeee.csv')
for i in df.to_numpy():
  print(i)

[1 'John Doe' 'Sales' 60000 '2022-01-15']
[2 'Jane Smith' 'Marketing' 55000 '2021-03-22']
[3 'Emily Davis' 'IT' 70000 '2020-11-10']
[4 'Michael Brown' 'HR' 45000 '2023-07-30']
[5 'Sarah Wilson' 'Sales' 48000 '2022-09-15']
[6 'Jessica Lee' 'Sales' 62000 '2022-05-01']
[7 'Peter Pan' 'IT' 71000 '2021-12-23']
[8 'Alice Cooper' 'HR' 46000 '2023-01-25']
[9 'Robert Gray' 'Marketing' 57000 '2021-09-10']
[10 'Lily Collins' 'HR' 47000 '2023-02-14']

## **4. Write a Python program to read specific columns of a given CSV file and print the content of the columns**

In [ ]:
df[['name', 'salary']]

            name  salary
0       John Doe   60000
1     Jane Smith   55000
2    Emily Davis   70000
3  Michael Brown   45000
4   Sarah Wilson   48000
5    Jessica Lee   62000
6      Peter Pan   71000
7   Alice Cooper   46000
8    Robert Gray   57000
9   Lily Collins   47000

## **5. Write a Python program to write a Python dictionary to a csv file. After writing the CSV file read the CSV file and display the content.**

In [ ]:
dict = {'Name': ['Damon','Klaus','Kol','Hope','Elena'],
        'Age': [45,60,45,23,32],
        'Gender': ['Male','Male','Male','Female','Female']}
df = pd.DataFrame(dict)
df.to_csv("sample.csv", index=False)
print("Data written to sample.csv successfully.")
df_read = pd.read_csv("sample.csv")
print("\nCSV File Content:")
df_read.head()

Data written to sample.csv successfully.

CSV File Content:

    Name  Age  Gender
0  Damon   45    Male
1  Klaus   60    Male
2    Kol   45    Male
3   Hope   23  Female
4  Elena   32  Female